[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 10
  [de.params]
    languageISO = "DE"
    titleAddition = "CloudPBX Dokumentation"
    description = "NetCologne CloudPBX Dokumentation."
    titleHome = "CloudPBX Dokumentation"
    footer = "© NetCologne GmbH 2022 <a href=\"https://www.netcologne.de/impressum/\">Impressum</a>, <a href=\"https://www.netcologne.de/agb/\">AGB</a>, <a href=\"https://www.netcologne.de/datenschutz/\">Datenschutz</a>"

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 20
  [en.params]
    languageISO = "EN"

