[[main]]
  name = "Dokumentation"
  weight = 5
  url = "/docs/grundlagen/voraussetzungen"

[[docs]]
  name = "Grundlagen"
  weight = 10
  identifier = "grundlagen"
  url = "/docs/grundlagen/"

[[docs]]
  name = "Konfiguration"
  weight = 20
  identifier = "konfiguration"
  url = "/docs/konfiguration/"



[[docs]]
  name = "Funktionen"
  weight = 40
  identifier = "funktionen"
  url = "/docs/funktionen/"

[[docs]]
  name = "Endgeräte"
  weight = 50
  identifier = "endgeraete"
  url = "/docs/endgeraete/"

[[docs]]
  name = "Problemlösungen"
  weight = 60
  identifier = "problemloesungen"
  url = "/docs/problemloesungen/"

#[[social]]
#  name = "Twitter"
#  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#  url = "https://twitter.com/netcolognenews?lang=de"
#  weight = 10

[[footer]]
  name = "Tel: 	0221 2222 995"
  url = "https://www.netcologne.de/geschaeftskunden/kontakt/kontaktformular/"
  weight = 10
